aedatastore/doc.go
clouddatastore/doc.go

Add more custom import path checking.
The sub-packages also need custom import path check magic comment.
ref: https://github.com/uber-go/zap/blob/f85c78b1dd998214c5f2138155b320a4a43fbe36/zapcore/doc.go#L24

Add more custom import path checking

---

.circleci/config.yml
README.md
test.sh

feat(ci): add .circleci/config.yml

---

LICENSE.goon
README.md
boom/README.md
boom/batch.go
boom/batch_test.go
boom/boom.go
boom/boom_test.go
boom/doc.go
boom/interfaces.go
boom/query.go
boom/query_test.go
boom/transaction.go
boom/transaction_test.go
boom/tx_batch.go
boom/tx_batch_test.go
internal/testutils/testutils.go
load.go
test.sh

I ❤️  https://github.com/mjibson/goon 🐈 
TODO

boom - goon compat library for datastore wrapper

---

boom/transaction.go

for compatibility between *boom.Boom to *boom.Transaction.

feat(boom): add Kind, Key, KeyError method to *boom.Transaction

---

boom/boom.go
boom/boom_test.go

fix(boom): fix nil parent key handling

---

README.md
aedatastore/bridge.go
aedatastore/client.go
caches.go
clouddatastore/bridge.go
clouddatastore/client.go
clouddatastore/testsuite_test.go
dsmiddleware/aememcache/aememcache.go
dsmiddleware/chaosrpc/chaosrpc.go
dsmiddleware/dslog/dslog.go
dsmiddleware/dslog/dslog_test.go
dsmiddleware/fishbone/fishbone.go
dsmiddleware/localcache/localcache.go
dsmiddleware/noop/noop.go
dsmiddleware/rediscache/rediscache.go
dsmiddleware/rpcretry/glitch_emulator_test.go
dsmiddleware/rpcretry/rpcretry.go
dsmiddleware/rpcretry/rpcretry_test.go
dsmiddleware/storagecache/storagecache.go
internal/shared/middleware_bridge.go
testsuite/dsmiddleware/dslog/dslog.go
testsuite/dsmiddleware/rpcretry/glitch_emulator.go
testsuite/dsmiddleware/rpcretry/rpcretry.go

I want to covering all RPC methods in Middleware interface.
need more tests?

add AllocateIDs & Count method to Middleware interface

---

boom/transaction.go

closes #47
@soundTricker added it!

feat(boom): add DatastoreTransaction function to boom package

---

clouddatastore/bridge.go

It required that use Cloud Datastore in go111 environment smoothly.

feat(cloud): add FromClient function

---

clouddatastore/bridge.go
go.mod
internal/option.go
option.go

feat(cloud): add WithGRPCDialOption option

---

dsmiddleware/rpcretry/rpcretry.go
dsmiddleware/rpcretry/rpcretry_test.go

refactor & update tests from #62

---

clouddatastore/convert.go

Fix encoding issue on embedded entity.

---

clouddatastore/testsuite_test.go
dsmiddleware/dsmemcache/doc.go

add more test & docs to dsmiddleware/dsmemcache

---

clouddatastore/testsuite_test.go
dsmiddleware/splitop/option.go
dsmiddleware/splitop/splitcall.go
dsmiddleware/splitop/splitcall_test.go

feat(dsmiddleware/splitop): implement Put timing operation

---

save.go

fix(core): allow nil when PropertyTranslator returns nil value

---

boom/boom.go
boom/boom_test.go

feat(boom): support PropertyTranslator return Key with ParentKey

---

aedatastore/query.go
caches.go
clouddatastore/query.go
interfaces.go

Support DistinctOn method

---

dsmiddleware/rpcretry/rpcretry.go

feat(dsmiddleware/rpcretry): don't retry when receive definitive error

---

package-lock.json
package.json

chore(deps): update npm dependencies

---

.github/workflows/cicd.yml

feat(ci): add .github/workflows/cicd.yml

---

.github/workflows/cicd.yml
v2/go.mod
v2/main.go

feat(ci): prepare v2

---

.github/workflows/cicd.yml

feat(ci): test v1 with go 1.11 only

---

README.md
v2/README.md

docs(core): update README.md
